// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: dashboard.proto

package dashboard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	EventId       string                 `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Event) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type Tile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PosDevices       int32                  `protobuf:"varint,1,opt,name=pos_devices,json=posDevices,proto3" json:"pos_devices,omitempty"`
	ActiveDevices    int32                  `protobuf:"varint,2,opt,name=active_devices,json=activeDevices,proto3" json:"active_devices,omitempty"`
	OfflineDevices   int32                  `protobuf:"varint,3,opt,name=offline_devices,json=offlineDevices,proto3" json:"offline_devices,omitempty"`
	Apps             int32                  `protobuf:"varint,4,opt,name=apps,proto3" json:"apps,omitempty"`
	AppVersion       string                 `protobuf:"bytes,5,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	LocationsTracked int32                  `protobuf:"varint,6,opt,name=locations_tracked,json=locationsTracked,proto3" json:"locations_tracked,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Tile) Reset() {
	*x = Tile{}
	mi := &file_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile) ProtoMessage() {}

func (x *Tile) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile.ProtoReflect.Descriptor instead.
func (*Tile) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *Tile) GetPosDevices() int32 {
	if x != nil {
		return x.PosDevices
	}
	return 0
}

func (x *Tile) GetActiveDevices() int32 {
	if x != nil {
		return x.ActiveDevices
	}
	return 0
}

func (x *Tile) GetOfflineDevices() int32 {
	if x != nil {
		return x.OfflineDevices
	}
	return 0
}

func (x *Tile) GetApps() int32 {
	if x != nil {
		return x.Apps
	}
	return 0
}

func (x *Tile) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *Tile) GetLocationsTracked() int32 {
	if x != nil {
		return x.LocationsTracked
	}
	return 0
}

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=searchQuery,proto3" json:"searchQuery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetEventsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetTileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tile          []*Tile                `protobuf:"bytes,1,rep,name=tile,proto3" json:"tile,omitempty"`                // List of users
	TotalPages    int32                  `protobuf:"varint,2,opt,name=totalPages,proto3" json:"totalPages,omitempty"`   // Total number of pages
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"` // Current page
	HasMore       bool                   `protobuf:"varint,4,opt,name=hasMore,proto3" json:"hasMore,omitempty"`         // Whether there are more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTileInfoResponse) Reset() {
	*x = GetTileInfoResponse{}
	mi := &file_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTileInfoResponse) ProtoMessage() {}

func (x *GetTileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTileInfoResponse.ProtoReflect.Descriptor instead.
func (*GetTileInfoResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetTileInfoResponse) GetTile() []*Tile {
	if x != nil {
		return x.Tile
	}
	return nil
}

func (x *GetTileInfoResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetTileInfoResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetTileInfoResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         []*Event               `protobuf:"bytes,1,rep,name=event,proto3" json:"event,omitempty"`              // List of users
	TotalPages    int32                  `protobuf:"varint,2,opt,name=totalPages,proto3" json:"totalPages,omitempty"`   // Total number of pages
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"` // Current page
	HasMore       bool                   `protobuf:"varint,4,opt,name=hasMore,proto3" json:"hasMore,omitempty"`         // Whether there are more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventsResponse) GetEvent() []*Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GetEventsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetEventsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetEventsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ChartDataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`  // e.g., "offline", "v1.2.0"
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // e.g., device count
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`  // optional: "var(--chart-1)"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChartDataPoint) Reset() {
	*x = ChartDataPoint{}
	mi := &file_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartDataPoint) ProtoMessage() {}

func (x *ChartDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartDataPoint.ProtoReflect.Descriptor instead.
func (*ChartDataPoint) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *ChartDataPoint) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ChartDataPoint) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ChartDataPoint) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

// General chart meta info
type ChartMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // e.g., "pie", "bar"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChartMeta) Reset() {
	*x = ChartMeta{}
	mi := &file_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartMeta) ProtoMessage() {}

func (x *ChartMeta) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartMeta.ProtoReflect.Descriptor instead.
func (*ChartMeta) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *ChartMeta) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChartMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChartMeta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Pie chart response
type PieChartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ChartMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          []*ChartDataPoint      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PieChartResponse) Reset() {
	*x = PieChartResponse{}
	mi := &file_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PieChartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieChartResponse) ProtoMessage() {}

func (x *PieChartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieChartResponse.ProtoReflect.Descriptor instead.
func (*PieChartResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{7}
}

func (x *PieChartResponse) GetMeta() *ChartMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PieChartResponse) GetData() []*ChartDataPoint {
	if x != nil {
		return x.Data
	}
	return nil
}

// Bar chart response
type BarChartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ChartMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          []*ChartDataPoint      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarChartResponse) Reset() {
	*x = BarChartResponse{}
	mi := &file_dashboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarChartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarChartResponse) ProtoMessage() {}

func (x *BarChartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarChartResponse.ProtoReflect.Descriptor instead.
func (*BarChartResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{8}
}

func (x *BarChartResponse) GetMeta() *ChartMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *BarChartResponse) GetData() []*ChartDataPoint {
	if x != nil {
		return x.Data
	}
	return nil
}

// Unified chart response if you want polymorphism
type DashboardChartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieChart      *PieChartResponse      `protobuf:"bytes,1,opt,name=pie_chart,json=pieChart,proto3" json:"pie_chart,omitempty"`
	BarChart      *BarChartResponse      `protobuf:"bytes,2,opt,name=bar_chart,json=barChart,proto3" json:"bar_chart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardChartsResponse) Reset() {
	*x = DashboardChartsResponse{}
	mi := &file_dashboard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardChartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardChartsResponse) ProtoMessage() {}

func (x *DashboardChartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardChartsResponse.ProtoReflect.Descriptor instead.
func (*DashboardChartsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{9}
}

func (x *DashboardChartsResponse) GetPieChart() *PieChartResponse {
	if x != nil {
		return x.PieChart
	}
	return nil
}

func (x *DashboardChartsResponse) GetBarChart() *BarChartResponse {
	if x != nil {
		return x.BarChart
	}
	return nil
}

var File_dashboard_proto protoreflect.FileDescriptor

const file_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x0fdashboard.proto\x12\tdashboard\"h\n" +
	"\x05Event\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\"\xd9\x01\n" +
	"\x04Tile\x12\x1f\n" +
	"\vpos_devices\x18\x01 \x01(\x05R\n" +
	"posDevices\x12%\n" +
	"\x0eactive_devices\x18\x02 \x01(\x05R\ractiveDevices\x12'\n" +
	"\x0foffline_devices\x18\x03 \x01(\x05R\x0eofflineDevices\x12\x12\n" +
	"\x04apps\x18\x04 \x01(\x05R\x04apps\x12\x1f\n" +
	"\vapp_version\x18\x05 \x01(\tR\n" +
	"appVersion\x12+\n" +
	"\x11locations_tracked\x18\x06 \x01(\x05R\x10locationsTracked\"d\n" +
	"\x10GetEventsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12 \n" +
	"\vsearchQuery\x18\x03 \x01(\tR\vsearchQuery\"\x96\x01\n" +
	"\x13GetTileInfoResponse\x12#\n" +
	"\x04tile\x18\x01 \x03(\v2\x0f.dashboard.TileR\x04tile\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12 \n" +
	"\vcurrentPage\x18\x03 \x01(\x05R\vcurrentPage\x12\x18\n" +
	"\ahasMore\x18\x04 \x01(\bR\ahasMore\"\x97\x01\n" +
	"\x11GetEventsResponse\x12&\n" +
	"\x05event\x18\x01 \x03(\v2\x10.dashboard.EventR\x05event\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12 \n" +
	"\vcurrentPage\x18\x03 \x01(\x05R\vcurrentPage\x12\x18\n" +
	"\ahasMore\x18\x04 \x01(\bR\ahasMore\"R\n" +
	"\x0eChartDataPoint\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"W\n" +
	"\tChartMeta\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"k\n" +
	"\x10PieChartResponse\x12(\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.dashboard.ChartMetaR\x04meta\x12-\n" +
	"\x04data\x18\x02 \x03(\v2\x19.dashboard.ChartDataPointR\x04data\"k\n" +
	"\x10BarChartResponse\x12(\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.dashboard.ChartMetaR\x04meta\x12-\n" +
	"\x04data\x18\x02 \x03(\v2\x19.dashboard.ChartDataPointR\x04data\"\x8d\x01\n" +
	"\x17DashboardChartsResponse\x128\n" +
	"\tpie_chart\x18\x01 \x01(\v2\x1b.dashboard.PieChartResponseR\bpieChart\x128\n" +
	"\tbar_chart\x18\x02 \x01(\v2\x1b.dashboard.BarChartResponseR\bbarChartB\x1cZ\x1a/proto/dashboard;dashboardb\x06proto3"

var (
	file_dashboard_proto_rawDescOnce sync.Once
	file_dashboard_proto_rawDescData []byte
)

func file_dashboard_proto_rawDescGZIP() []byte {
	file_dashboard_proto_rawDescOnce.Do(func() {
		file_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)))
	})
	return file_dashboard_proto_rawDescData
}

var file_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_dashboard_proto_goTypes = []any{
	(*Event)(nil),                   // 0: dashboard.Event
	(*Tile)(nil),                    // 1: dashboard.Tile
	(*GetEventsRequest)(nil),        // 2: dashboard.GetEventsRequest
	(*GetTileInfoResponse)(nil),     // 3: dashboard.GetTileInfoResponse
	(*GetEventsResponse)(nil),       // 4: dashboard.GetEventsResponse
	(*ChartDataPoint)(nil),          // 5: dashboard.ChartDataPoint
	(*ChartMeta)(nil),               // 6: dashboard.ChartMeta
	(*PieChartResponse)(nil),        // 7: dashboard.PieChartResponse
	(*BarChartResponse)(nil),        // 8: dashboard.BarChartResponse
	(*DashboardChartsResponse)(nil), // 9: dashboard.DashboardChartsResponse
}
var file_dashboard_proto_depIdxs = []int32{
	1, // 0: dashboard.GetTileInfoResponse.tile:type_name -> dashboard.Tile
	0, // 1: dashboard.GetEventsResponse.event:type_name -> dashboard.Event
	6, // 2: dashboard.PieChartResponse.meta:type_name -> dashboard.ChartMeta
	5, // 3: dashboard.PieChartResponse.data:type_name -> dashboard.ChartDataPoint
	6, // 4: dashboard.BarChartResponse.meta:type_name -> dashboard.ChartMeta
	5, // 5: dashboard.BarChartResponse.data:type_name -> dashboard.ChartDataPoint
	7, // 6: dashboard.DashboardChartsResponse.pie_chart:type_name -> dashboard.PieChartResponse
	8, // 7: dashboard.DashboardChartsResponse.bar_chart:type_name -> dashboard.BarChartResponse
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_dashboard_proto_init() }
func file_dashboard_proto_init() {
	if File_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dashboard_proto_goTypes,
		DependencyIndexes: file_dashboard_proto_depIdxs,
		MessageInfos:      file_dashboard_proto_msgTypes,
	}.Build()
	File_dashboard_proto = out.File
	file_dashboard_proto_goTypes = nil
	file_dashboard_proto_depIdxs = nil
}
