// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: business.proto

package business

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusinessRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	File          []byte                 `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessRegisterRequest) Reset() {
	*x = BusinessRegisterRequest{}
	mi := &file_business_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessRegisterRequest) ProtoMessage() {}

func (x *BusinessRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessRegisterRequest.ProtoReflect.Descriptor instead.
func (*BusinessRegisterRequest) Descriptor() ([]byte, []int) {
	return file_business_proto_rawDescGZIP(), []int{0}
}

func (x *BusinessRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BusinessRegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BusinessRegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BusinessRegisterRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *BusinessRegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type Business struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Status        bool                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	BusinessLogo  string                 `protobuf:"bytes,6,opt,name=business_logo,json=businessLogo,proto3" json:"business_logo,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Device        []*PosDevice           `protobuf:"bytes,8,rep,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Business) Reset() {
	*x = Business{}
	mi := &file_business_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Business) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Business) ProtoMessage() {}

func (x *Business) ProtoReflect() protoreflect.Message {
	mi := &file_business_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Business.ProtoReflect.Descriptor instead.
func (*Business) Descriptor() ([]byte, []int) {
	return file_business_proto_rawDescGZIP(), []int{1}
}

func (x *Business) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Business) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Business) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Business) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Business) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Business) GetBusinessLogo() string {
	if x != nil {
		return x.BusinessLogo
	}
	return ""
}

func (x *Business) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Business) GetDevice() []*PosDevice {
	if x != nil {
		return x.Device
	}
	return nil
}

type GetBusinessesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=searchQuery,proto3" json:"searchQuery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusinessesRequest) Reset() {
	*x = GetBusinessesRequest{}
	mi := &file_business_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusinessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessesRequest) ProtoMessage() {}

func (x *GetBusinessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessesRequest.ProtoReflect.Descriptor instead.
func (*GetBusinessesRequest) Descriptor() ([]byte, []int) {
	return file_business_proto_rawDescGZIP(), []int{2}
}

func (x *GetBusinessesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBusinessesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetBusinessesRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetBusinessesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Business      []*Business            `protobuf:"bytes,1,rep,name=business,proto3" json:"business,omitempty"`        // List of users
	TotalPages    int32                  `protobuf:"varint,2,opt,name=totalPages,proto3" json:"totalPages,omitempty"`   // Total number of pages
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"` // Current page
	HasMore       bool                   `protobuf:"varint,4,opt,name=hasMore,proto3" json:"hasMore,omitempty"`         // Whether there are more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusinessesResponse) Reset() {
	*x = GetBusinessesResponse{}
	mi := &file_business_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusinessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessesResponse) ProtoMessage() {}

func (x *GetBusinessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_business_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessesResponse.ProtoReflect.Descriptor instead.
func (*GetBusinessesResponse) Descriptor() ([]byte, []int) {
	return file_business_proto_rawDescGZIP(), []int{3}
}

func (x *GetBusinessesResponse) GetBusiness() []*Business {
	if x != nil {
		return x.Business
	}
	return nil
}

func (x *GetBusinessesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetBusinessesResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetBusinessesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditBusinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Status        bool                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	BusinessLogo  []byte                 `protobuf:"bytes,6,opt,name=business_logo,json=businessLogo,proto3" json:"business_logo,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditBusinessRequest) Reset() {
	*x = EditBusinessRequest{}
	mi := &file_business_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditBusinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditBusinessRequest) ProtoMessage() {}

func (x *EditBusinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditBusinessRequest.ProtoReflect.Descriptor instead.
func (*EditBusinessRequest) Descriptor() ([]byte, []int) {
	return file_business_proto_rawDescGZIP(), []int{4}
}

func (x *EditBusinessRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditBusinessRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EditBusinessRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EditBusinessRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditBusinessRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *EditBusinessRequest) GetBusinessLogo() []byte {
	if x != nil {
		return x.BusinessLogo
	}
	return nil
}

func (x *EditBusinessRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type PosDevice struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AppId               string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	SerialNumber        string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CurrentAppVersion   string                 `protobuf:"bytes,4,opt,name=current_app_version,json=currentAppVersion,proto3" json:"current_app_version,omitempty"`
	LastKnownLatitude   string                 `protobuf:"bytes,5,opt,name=last_known_latitude,json=lastKnownLatitude,proto3" json:"last_known_latitude,omitempty"`
	LastKnownLongitude  string                 `protobuf:"bytes,6,opt,name=last_known_longitude,json=lastKnownLongitude,proto3" json:"last_known_longitude,omitempty"`
	Status              string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	DeviceModel         string                 `protobuf:"bytes,8,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	OperatingSystem     string                 `protobuf:"bytes,9,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	Id                  string                 `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	LocationLastUpdated string                 `protobuf:"bytes,11,opt,name=location_last_updated,json=locationLastUpdated,proto3" json:"location_last_updated,omitempty"`
	Description         string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	BusinessName        string                 `protobuf:"bytes,13,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	Fingerprint         string                 `protobuf:"bytes,14,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PosDevice) Reset() {
	*x = PosDevice{}
	mi := &file_business_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosDevice) ProtoMessage() {}

func (x *PosDevice) ProtoReflect() protoreflect.Message {
	mi := &file_business_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosDevice.ProtoReflect.Descriptor instead.
func (*PosDevice) Descriptor() ([]byte, []int) {
	return file_business_proto_rawDescGZIP(), []int{5}
}

func (x *PosDevice) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *PosDevice) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *PosDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PosDevice) GetCurrentAppVersion() string {
	if x != nil {
		return x.CurrentAppVersion
	}
	return ""
}

func (x *PosDevice) GetLastKnownLatitude() string {
	if x != nil {
		return x.LastKnownLatitude
	}
	return ""
}

func (x *PosDevice) GetLastKnownLongitude() string {
	if x != nil {
		return x.LastKnownLongitude
	}
	return ""
}

func (x *PosDevice) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PosDevice) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *PosDevice) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *PosDevice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PosDevice) GetLocationLastUpdated() string {
	if x != nil {
		return x.LocationLastUpdated
	}
	return ""
}

func (x *PosDevice) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PosDevice) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *PosDevice) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

var File_business_proto protoreflect.FileDescriptor

const file_business_proto_rawDesc = "" +
	"\n" +
	"\x0ebusiness.proto\x12\bbusiness\"\x87\x01\n" +
	"\x17BusinessRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04file\x18\x04 \x01(\fR\x04file\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\"\xde\x01\n" +
	"\bBusiness\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\x12#\n" +
	"\rbusiness_logo\x18\x06 \x01(\tR\fbusinessLogo\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12+\n" +
	"\x06device\x18\b \x03(\v2\x13.business.PosDeviceR\x06device\"h\n" +
	"\x14GetBusinessesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12 \n" +
	"\vsearchQuery\x18\x03 \x01(\tR\vsearchQuery\"\xa3\x01\n" +
	"\x15GetBusinessesResponse\x12.\n" +
	"\bbusiness\x18\x01 \x03(\v2\x12.business.BusinessR\bbusiness\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12 \n" +
	"\vcurrentPage\x18\x03 \x01(\x05R\vcurrentPage\x12\x18\n" +
	"\ahasMore\x18\x04 \x01(\bR\ahasMore\"\xbc\x01\n" +
	"\x13EditBusinessRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\x12#\n" +
	"\rbusiness_logo\x18\x06 \x01(\fR\fbusinessLogo\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\"\x80\x04\n" +
	"\tPosDevice\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12.\n" +
	"\x13current_app_version\x18\x04 \x01(\tR\x11currentAppVersion\x12.\n" +
	"\x13last_known_latitude\x18\x05 \x01(\tR\x11lastKnownLatitude\x120\n" +
	"\x14last_known_longitude\x18\x06 \x01(\tR\x12lastKnownLongitude\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12!\n" +
	"\fdevice_model\x18\b \x01(\tR\vdeviceModel\x12)\n" +
	"\x10operating_system\x18\t \x01(\tR\x0foperatingSystem\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\tR\x02id\x122\n" +
	"\x15location_last_updated\x18\v \x01(\tR\x13locationLastUpdated\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12#\n" +
	"\rbusiness_name\x18\r \x01(\tR\fbusinessName\x12 \n" +
	"\vfingerprint\x18\x0e \x01(\tR\vfingerprintB\x1aZ\x18/proto/business;businessb\x06proto3"

var (
	file_business_proto_rawDescOnce sync.Once
	file_business_proto_rawDescData []byte
)

func file_business_proto_rawDescGZIP() []byte {
	file_business_proto_rawDescOnce.Do(func() {
		file_business_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_business_proto_rawDesc), len(file_business_proto_rawDesc)))
	})
	return file_business_proto_rawDescData
}

var file_business_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_business_proto_goTypes = []any{
	(*BusinessRegisterRequest)(nil), // 0: business.BusinessRegisterRequest
	(*Business)(nil),                // 1: business.Business
	(*GetBusinessesRequest)(nil),    // 2: business.GetBusinessesRequest
	(*GetBusinessesResponse)(nil),   // 3: business.GetBusinessesResponse
	(*EditBusinessRequest)(nil),     // 4: business.EditBusinessRequest
	(*PosDevice)(nil),               // 5: business.PosDevice
}
var file_business_proto_depIdxs = []int32{
	5, // 0: business.Business.device:type_name -> business.PosDevice
	1, // 1: business.GetBusinessesResponse.business:type_name -> business.Business
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_business_proto_init() }
func file_business_proto_init() {
	if File_business_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_business_proto_rawDesc), len(file_business_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_business_proto_goTypes,
		DependencyIndexes: file_business_proto_depIdxs,
		MessageInfos:      file_business_proto_msgTypes,
	}.Build()
	File_business_proto = out.File
	file_business_proto_goTypes = nil
	file_business_proto_depIdxs = nil
}
