// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: pos_devices.proto

package posdevices

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterPosDeviceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string app_id = 1;
	SerialNumber       string `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Name               string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CurrentAppVersion  string `protobuf:"bytes,4,opt,name=current_app_version,json=currentAppVersion,proto3" json:"current_app_version,omitempty"`
	LastKnownLatitude  string `protobuf:"bytes,5,opt,name=last_known_latitude,json=lastKnownLatitude,proto3" json:"last_known_latitude,omitempty"`
	LastKnownLongitude string `protobuf:"bytes,6,opt,name=last_known_longitude,json=lastKnownLongitude,proto3" json:"last_known_longitude,omitempty"`
	Status             string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	DeviceModel        string `protobuf:"bytes,8,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	OperatingSystem    string `protobuf:"bytes,9,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	Description        string `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Email              string `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
	BusinessName       string `protobuf:"bytes,12,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	Fingerprint        string `protobuf:"bytes,13,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	PhoneNumber1       string `protobuf:"bytes,14,opt,name=phone_number1,json=phoneNumber1,proto3" json:"phone_number1,omitempty"`
	PhoneNumber2       string `protobuf:"bytes,15,opt,name=phone_number2,json=phoneNumber2,proto3" json:"phone_number2,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterPosDeviceRequest) Reset() {
	*x = RegisterPosDeviceRequest{}
	mi := &file_pos_devices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPosDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPosDeviceRequest) ProtoMessage() {}

func (x *RegisterPosDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pos_devices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPosDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterPosDeviceRequest) Descriptor() ([]byte, []int) {
	return file_pos_devices_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterPosDeviceRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *RegisterPosDeviceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterPosDeviceRequest) GetCurrentAppVersion() string {
	if x != nil {
		return x.CurrentAppVersion
	}
	return ""
}

func (x *RegisterPosDeviceRequest) GetLastKnownLatitude() string {
	if x != nil {
		return x.LastKnownLatitude
	}
	return ""
}

func (x *RegisterPosDeviceRequest) GetLastKnownLongitude() string {
	if x != nil {
		return x.LastKnownLongitude
	}
	return ""
}

func (x *RegisterPosDeviceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterPosDeviceRequest) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *RegisterPosDeviceRequest) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *RegisterPosDeviceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterPosDeviceRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterPosDeviceRequest) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *RegisterPosDeviceRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *RegisterPosDeviceRequest) GetPhoneNumber1() string {
	if x != nil {
		return x.PhoneNumber1
	}
	return ""
}

func (x *RegisterPosDeviceRequest) GetPhoneNumber2() string {
	if x != nil {
		return x.PhoneNumber2
	}
	return ""
}

type PosDevice struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AppId               string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	SerialNumber        string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CurrentAppVersion   string                 `protobuf:"bytes,4,opt,name=current_app_version,json=currentAppVersion,proto3" json:"current_app_version,omitempty"`
	LastKnownLatitude   string                 `protobuf:"bytes,5,opt,name=last_known_latitude,json=lastKnownLatitude,proto3" json:"last_known_latitude,omitempty"`
	LastKnownLongitude  string                 `protobuf:"bytes,6,opt,name=last_known_longitude,json=lastKnownLongitude,proto3" json:"last_known_longitude,omitempty"`
	Status              string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	DeviceModel         string                 `protobuf:"bytes,8,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	OperatingSystem     string                 `protobuf:"bytes,9,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	Id                  string                 `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	LocationLastUpdated string                 `protobuf:"bytes,11,opt,name=location_last_updated,json=locationLastUpdated,proto3" json:"location_last_updated,omitempty"`
	Description         string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	BusinessName        string                 `protobuf:"bytes,13,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	Fingerprint         string                 `protobuf:"bytes,14,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	PhoneNumber1        string                 `protobuf:"bytes,15,opt,name=phone_number1,json=phoneNumber1,proto3" json:"phone_number1,omitempty"`
	PhoneNumber2        string                 `protobuf:"bytes,16,opt,name=phone_number2,json=phoneNumber2,proto3" json:"phone_number2,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PosDevice) Reset() {
	*x = PosDevice{}
	mi := &file_pos_devices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosDevice) ProtoMessage() {}

func (x *PosDevice) ProtoReflect() protoreflect.Message {
	mi := &file_pos_devices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosDevice.ProtoReflect.Descriptor instead.
func (*PosDevice) Descriptor() ([]byte, []int) {
	return file_pos_devices_proto_rawDescGZIP(), []int{1}
}

func (x *PosDevice) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *PosDevice) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *PosDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PosDevice) GetCurrentAppVersion() string {
	if x != nil {
		return x.CurrentAppVersion
	}
	return ""
}

func (x *PosDevice) GetLastKnownLatitude() string {
	if x != nil {
		return x.LastKnownLatitude
	}
	return ""
}

func (x *PosDevice) GetLastKnownLongitude() string {
	if x != nil {
		return x.LastKnownLongitude
	}
	return ""
}

func (x *PosDevice) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PosDevice) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *PosDevice) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *PosDevice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PosDevice) GetLocationLastUpdated() string {
	if x != nil {
		return x.LocationLastUpdated
	}
	return ""
}

func (x *PosDevice) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PosDevice) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *PosDevice) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *PosDevice) GetPhoneNumber1() string {
	if x != nil {
		return x.PhoneNumber1
	}
	return ""
}

func (x *PosDevice) GetPhoneNumber2() string {
	if x != nil {
		return x.PhoneNumber2
	}
	return ""
}

type GetPosDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=searchQuery,proto3" json:"searchQuery,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	AppVersion    string                 `protobuf:"bytes,6,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPosDevicesRequest) Reset() {
	*x = GetPosDevicesRequest{}
	mi := &file_pos_devices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPosDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPosDevicesRequest) ProtoMessage() {}

func (x *GetPosDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pos_devices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPosDevicesRequest.ProtoReflect.Descriptor instead.
func (*GetPosDevicesRequest) Descriptor() ([]byte, []int) {
	return file_pos_devices_proto_rawDescGZIP(), []int{2}
}

func (x *GetPosDevicesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPosDevicesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetPosDevicesRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *GetPosDevicesRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetPosDevicesRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetPosDevicesRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type GetPosDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posdevice     []*PosDevice           `protobuf:"bytes,1,rep,name=posdevice,proto3" json:"posdevice,omitempty"`      // List of users
	TotalPages    int32                  `protobuf:"varint,2,opt,name=totalPages,proto3" json:"totalPages,omitempty"`   // Total number of pages
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"` // Current page
	HasMore       bool                   `protobuf:"varint,4,opt,name=hasMore,proto3" json:"hasMore,omitempty"`         // Whether there are more pages
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPosDevicesResponse) Reset() {
	*x = GetPosDevicesResponse{}
	mi := &file_pos_devices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPosDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPosDevicesResponse) ProtoMessage() {}

func (x *GetPosDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pos_devices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPosDevicesResponse.ProtoReflect.Descriptor instead.
func (*GetPosDevicesResponse) Descriptor() ([]byte, []int) {
	return file_pos_devices_proto_rawDescGZIP(), []int{3}
}

func (x *GetPosDevicesResponse) GetPosdevice() []*PosDevice {
	if x != nil {
		return x.Posdevice
	}
	return nil
}

func (x *GetPosDevicesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetPosDevicesResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetPosDevicesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetPosDevicesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type EditPosDeviceRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AppId              string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	SerialNumber       string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CurrentAppVersion  string                 `protobuf:"bytes,4,opt,name=current_app_version,json=currentAppVersion,proto3" json:"current_app_version,omitempty"`
	LastKnownLatitude  string                 `protobuf:"bytes,5,opt,name=last_known_latitude,json=lastKnownLatitude,proto3" json:"last_known_latitude,omitempty"`
	LastKnownLongitude string                 `protobuf:"bytes,6,opt,name=last_known_longitude,json=lastKnownLongitude,proto3" json:"last_known_longitude,omitempty"`
	Status             string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	DeviceModel        string                 `protobuf:"bytes,8,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	OperatingSystem    string                 `protobuf:"bytes,9,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	Id                 string                 `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	Description        string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	BusinessName       string                 `protobuf:"bytes,12,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	PhoneNumber1       string                 `protobuf:"bytes,13,opt,name=phone_number1,json=phoneNumber1,proto3" json:"phone_number1,omitempty"`
	PhoneNumber2       string                 `protobuf:"bytes,14,opt,name=phone_number2,json=phoneNumber2,proto3" json:"phone_number2,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EditPosDeviceRequest) Reset() {
	*x = EditPosDeviceRequest{}
	mi := &file_pos_devices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPosDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPosDeviceRequest) ProtoMessage() {}

func (x *EditPosDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pos_devices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPosDeviceRequest.ProtoReflect.Descriptor instead.
func (*EditPosDeviceRequest) Descriptor() ([]byte, []int) {
	return file_pos_devices_proto_rawDescGZIP(), []int{4}
}

func (x *EditPosDeviceRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *EditPosDeviceRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *EditPosDeviceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditPosDeviceRequest) GetCurrentAppVersion() string {
	if x != nil {
		return x.CurrentAppVersion
	}
	return ""
}

func (x *EditPosDeviceRequest) GetLastKnownLatitude() string {
	if x != nil {
		return x.LastKnownLatitude
	}
	return ""
}

func (x *EditPosDeviceRequest) GetLastKnownLongitude() string {
	if x != nil {
		return x.LastKnownLongitude
	}
	return ""
}

func (x *EditPosDeviceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditPosDeviceRequest) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *EditPosDeviceRequest) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *EditPosDeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditPosDeviceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EditPosDeviceRequest) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *EditPosDeviceRequest) GetPhoneNumber1() string {
	if x != nil {
		return x.PhoneNumber1
	}
	return ""
}

func (x *EditPosDeviceRequest) GetPhoneNumber2() string {
	if x != nil {
		return x.PhoneNumber2
	}
	return ""
}

type RegisterLocationHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PosdeviceId   string                 `protobuf:"bytes,1,opt,name=posdevice_id,json=posdeviceId,proto3" json:"posdevice_id,omitempty"`
	Longitude     string                 `protobuf:"bytes,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      string                 `protobuf:"bytes,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Accuracy      string                 `protobuf:"bytes,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	City          string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	IpAddress     string                 `protobuf:"bytes,8,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterLocationHistoryRequest) Reset() {
	*x = RegisterLocationHistoryRequest{}
	mi := &file_pos_devices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterLocationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterLocationHistoryRequest) ProtoMessage() {}

func (x *RegisterLocationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pos_devices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterLocationHistoryRequest.ProtoReflect.Descriptor instead.
func (*RegisterLocationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_pos_devices_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterLocationHistoryRequest) GetPosdeviceId() string {
	if x != nil {
		return x.PosdeviceId
	}
	return ""
}

func (x *RegisterLocationHistoryRequest) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *RegisterLocationHistoryRequest) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *RegisterLocationHistoryRequest) GetAccuracy() string {
	if x != nil {
		return x.Accuracy
	}
	return ""
}

func (x *RegisterLocationHistoryRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *RegisterLocationHistoryRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterLocationHistoryRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *RegisterLocationHistoryRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type LocationHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PosdeviceId   string                 `protobuf:"bytes,1,opt,name=posdevice_id,json=posdeviceId,proto3" json:"posdevice_id,omitempty"`
	Longitude     string                 `protobuf:"bytes,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      string                 `protobuf:"bytes,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Accuracy      string                 `protobuf:"bytes,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	DeviceName    string                 `protobuf:"bytes,7,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Date          string                 `protobuf:"bytes,8,opt,name=date,proto3" json:"date,omitempty"`
	Region        string                 `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`
	City          string                 `protobuf:"bytes,10,opt,name=city,proto3" json:"city,omitempty"`
	IpAddress     string                 `protobuf:"bytes,11,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	BusinessName  string                 `protobuf:"bytes,12,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationHistory) Reset() {
	*x = LocationHistory{}
	mi := &file_pos_devices_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationHistory) ProtoMessage() {}

func (x *LocationHistory) ProtoReflect() protoreflect.Message {
	mi := &file_pos_devices_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationHistory.ProtoReflect.Descriptor instead.
func (*LocationHistory) Descriptor() ([]byte, []int) {
	return file_pos_devices_proto_rawDescGZIP(), []int{6}
}

func (x *LocationHistory) GetPosdeviceId() string {
	if x != nil {
		return x.PosdeviceId
	}
	return ""
}

func (x *LocationHistory) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *LocationHistory) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *LocationHistory) GetAccuracy() string {
	if x != nil {
		return x.Accuracy
	}
	return ""
}

func (x *LocationHistory) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LocationHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LocationHistory) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *LocationHistory) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *LocationHistory) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *LocationHistory) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *LocationHistory) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *LocationHistory) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

type GetLocationHistorysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=searchQuery,proto3" json:"searchQuery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationHistorysRequest) Reset() {
	*x = GetLocationHistorysRequest{}
	mi := &file_pos_devices_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationHistorysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationHistorysRequest) ProtoMessage() {}

func (x *GetLocationHistorysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pos_devices_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationHistorysRequest.ProtoReflect.Descriptor instead.
func (*GetLocationHistorysRequest) Descriptor() ([]byte, []int) {
	return file_pos_devices_proto_rawDescGZIP(), []int{7}
}

func (x *GetLocationHistorysRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLocationHistorysRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetLocationHistorysRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetLocationHistorysResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LocationHistory []*LocationHistory     `protobuf:"bytes,1,rep,name=location_history,json=locationHistory,proto3" json:"location_history,omitempty"` // List of users
	TotalPages      int32                  `protobuf:"varint,2,opt,name=totalPages,proto3" json:"totalPages,omitempty"`                                 // Total number of pages
	CurrentPage     int32                  `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"`                               // Current page
	HasMore         bool                   `protobuf:"varint,4,opt,name=hasMore,proto3" json:"hasMore,omitempty"`                                       // Whether there are more pages
	Count           int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLocationHistorysResponse) Reset() {
	*x = GetLocationHistorysResponse{}
	mi := &file_pos_devices_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationHistorysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationHistorysResponse) ProtoMessage() {}

func (x *GetLocationHistorysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pos_devices_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationHistorysResponse.ProtoReflect.Descriptor instead.
func (*GetLocationHistorysResponse) Descriptor() ([]byte, []int) {
	return file_pos_devices_proto_rawDescGZIP(), []int{8}
}

func (x *GetLocationHistorysResponse) GetLocationHistory() []*LocationHistory {
	if x != nil {
		return x.LocationHistory
	}
	return nil
}

func (x *GetLocationHistorysResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetLocationHistorysResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetLocationHistorysResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetLocationHistorysResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type EditLocationHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PosdeviceId   string                 `protobuf:"bytes,1,opt,name=posdevice_id,json=posdeviceId,proto3" json:"posdevice_id,omitempty"`
	Longitude     string                 `protobuf:"bytes,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      string                 `protobuf:"bytes,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Accuracy      string                 `protobuf:"bytes,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Region        string                 `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	City          string                 `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	IpAddress     string                 `protobuf:"bytes,9,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditLocationHistoryRequest) Reset() {
	*x = EditLocationHistoryRequest{}
	mi := &file_pos_devices_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditLocationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditLocationHistoryRequest) ProtoMessage() {}

func (x *EditLocationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pos_devices_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditLocationHistoryRequest.ProtoReflect.Descriptor instead.
func (*EditLocationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_pos_devices_proto_rawDescGZIP(), []int{9}
}

func (x *EditLocationHistoryRequest) GetPosdeviceId() string {
	if x != nil {
		return x.PosdeviceId
	}
	return ""
}

func (x *EditLocationHistoryRequest) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *EditLocationHistoryRequest) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *EditLocationHistoryRequest) GetAccuracy() string {
	if x != nil {
		return x.Accuracy
	}
	return ""
}

func (x *EditLocationHistoryRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *EditLocationHistoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditLocationHistoryRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *EditLocationHistoryRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *EditLocationHistoryRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type CheckUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PosdeviceId   string                 `protobuf:"bytes,1,opt,name=posdevice_id,json=posdeviceId,proto3" json:"posdevice_id,omitempty"`
	AppVersion    string                 `protobuf:"bytes,2,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	BuildVersion  string                 `protobuf:"bytes,3,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUpdateRequest) Reset() {
	*x = CheckUpdateRequest{}
	mi := &file_pos_devices_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpdateRequest) ProtoMessage() {}

func (x *CheckUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pos_devices_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpdateRequest.ProtoReflect.Descriptor instead.
func (*CheckUpdateRequest) Descriptor() ([]byte, []int) {
	return file_pos_devices_proto_rawDescGZIP(), []int{10}
}

func (x *CheckUpdateRequest) GetPosdeviceId() string {
	if x != nil {
		return x.PosdeviceId
	}
	return ""
}

func (x *CheckUpdateRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *CheckUpdateRequest) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

type CheckUpdateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UpdateAvailable bool                   `protobuf:"varint,1,opt,name=update_available,json=updateAvailable,proto3" json:"update_available,omitempty"`
	LatestVersion   string                 `protobuf:"bytes,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	DownloadUrl     string                 `protobuf:"bytes,3,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	ReleaseNotes    string                 `protobuf:"bytes,4,opt,name=release_notes,json=releaseNotes,proto3" json:"release_notes,omitempty"`
	Code            int32                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckUpdateResponse) Reset() {
	*x = CheckUpdateResponse{}
	mi := &file_pos_devices_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpdateResponse) ProtoMessage() {}

func (x *CheckUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pos_devices_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpdateResponse.ProtoReflect.Descriptor instead.
func (*CheckUpdateResponse) Descriptor() ([]byte, []int) {
	return file_pos_devices_proto_rawDescGZIP(), []int{11}
}

func (x *CheckUpdateResponse) GetUpdateAvailable() bool {
	if x != nil {
		return x.UpdateAvailable
	}
	return false
}

func (x *CheckUpdateResponse) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *CheckUpdateResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *CheckUpdateResponse) GetReleaseNotes() string {
	if x != nil {
		return x.ReleaseNotes
	}
	return ""
}

func (x *CheckUpdateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_pos_devices_proto protoreflect.FileDescriptor

const file_pos_devices_proto_rawDesc = "" +
	"\n" +
	"\x11pos_devices.proto\x12\n" +
	"posdevices\"\x94\x04\n" +
	"\x18RegisterPosDeviceRequest\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12.\n" +
	"\x13current_app_version\x18\x04 \x01(\tR\x11currentAppVersion\x12.\n" +
	"\x13last_known_latitude\x18\x05 \x01(\tR\x11lastKnownLatitude\x120\n" +
	"\x14last_known_longitude\x18\x06 \x01(\tR\x12lastKnownLongitude\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12!\n" +
	"\fdevice_model\x18\b \x01(\tR\vdeviceModel\x12)\n" +
	"\x10operating_system\x18\t \x01(\tR\x0foperatingSystem\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x14\n" +
	"\x05email\x18\v \x01(\tR\x05email\x12#\n" +
	"\rbusiness_name\x18\f \x01(\tR\fbusinessName\x12 \n" +
	"\vfingerprint\x18\r \x01(\tR\vfingerprint\x12#\n" +
	"\rphone_number1\x18\x0e \x01(\tR\fphoneNumber1\x12#\n" +
	"\rphone_number2\x18\x0f \x01(\tR\fphoneNumber2\"\xca\x04\n" +
	"\tPosDevice\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12.\n" +
	"\x13current_app_version\x18\x04 \x01(\tR\x11currentAppVersion\x12.\n" +
	"\x13last_known_latitude\x18\x05 \x01(\tR\x11lastKnownLatitude\x120\n" +
	"\x14last_known_longitude\x18\x06 \x01(\tR\x12lastKnownLongitude\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12!\n" +
	"\fdevice_model\x18\b \x01(\tR\vdeviceModel\x12)\n" +
	"\x10operating_system\x18\t \x01(\tR\x0foperatingSystem\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\tR\x02id\x122\n" +
	"\x15location_last_updated\x18\v \x01(\tR\x13locationLastUpdated\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12#\n" +
	"\rbusiness_name\x18\r \x01(\tR\fbusinessName\x12 \n" +
	"\vfingerprint\x18\x0e \x01(\tR\vfingerprint\x12#\n" +
	"\rphone_number1\x18\x0f \x01(\tR\fphoneNumber1\x12#\n" +
	"\rphone_number2\x18\x10 \x01(\tR\fphoneNumber2\"\xc3\x01\n" +
	"\x14GetPosDevicesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12 \n" +
	"\vsearchQuery\x18\x03 \x01(\tR\vsearchQuery\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x1f\n" +
	"\vapp_version\x18\x06 \x01(\tR\n" +
	"appVersion\"\xbe\x01\n" +
	"\x15GetPosDevicesResponse\x123\n" +
	"\tposdevice\x18\x01 \x03(\v2\x15.posdevices.PosDeviceR\tposdevice\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12 \n" +
	"\vcurrentPage\x18\x03 \x01(\x05R\vcurrentPage\x12\x18\n" +
	"\ahasMore\x18\x04 \x01(\bR\ahasMore\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\"\xff\x03\n" +
	"\x14EditPosDeviceRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12.\n" +
	"\x13current_app_version\x18\x04 \x01(\tR\x11currentAppVersion\x12.\n" +
	"\x13last_known_latitude\x18\x05 \x01(\tR\x11lastKnownLatitude\x120\n" +
	"\x14last_known_longitude\x18\x06 \x01(\tR\x12lastKnownLongitude\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12!\n" +
	"\fdevice_model\x18\b \x01(\tR\vdeviceModel\x12)\n" +
	"\x10operating_system\x18\t \x01(\tR\x0foperatingSystem\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12#\n" +
	"\rbusiness_name\x18\f \x01(\tR\fbusinessName\x12#\n" +
	"\rphone_number1\x18\r \x01(\tR\fphoneNumber1\x12#\n" +
	"\rphone_number2\x18\x0e \x01(\tR\fphoneNumber2\"\x82\x02\n" +
	"\x1eRegisterLocationHistoryRequest\x12!\n" +
	"\fposdevice_id\x18\x01 \x01(\tR\vposdeviceId\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\tR\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\tR\blatitude\x12\x1a\n" +
	"\baccuracy\x18\x04 \x01(\tR\baccuracy\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12\x1d\n" +
	"\n" +
	"ip_address\x18\b \x01(\tR\tipAddress\"\xdd\x02\n" +
	"\x0fLocationHistory\x12!\n" +
	"\fposdevice_id\x18\x01 \x01(\tR\vposdeviceId\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\tR\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\tR\blatitude\x12\x1a\n" +
	"\baccuracy\x18\x04 \x01(\tR\baccuracy\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12\x1f\n" +
	"\vdevice_name\x18\a \x01(\tR\n" +
	"deviceName\x12\x12\n" +
	"\x04date\x18\b \x01(\tR\x04date\x12\x16\n" +
	"\x06region\x18\t \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\n" +
	" \x01(\tR\x04city\x12\x1d\n" +
	"\n" +
	"ip_address\x18\v \x01(\tR\tipAddress\x12#\n" +
	"\rbusiness_name\x18\f \x01(\tR\fbusinessName\"n\n" +
	"\x1aGetLocationHistorysRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12 \n" +
	"\vsearchQuery\x18\x03 \x01(\tR\vsearchQuery\"\xd7\x01\n" +
	"\x1bGetLocationHistorysResponse\x12F\n" +
	"\x10location_history\x18\x01 \x03(\v2\x1b.posdevices.LocationHistoryR\x0flocationHistory\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12 \n" +
	"\vcurrentPage\x18\x03 \x01(\x05R\vcurrentPage\x12\x18\n" +
	"\ahasMore\x18\x04 \x01(\bR\ahasMore\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\"\x8e\x02\n" +
	"\x1aEditLocationHistoryRequest\x12!\n" +
	"\fposdevice_id\x18\x01 \x01(\tR\vposdeviceId\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\tR\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\tR\blatitude\x12\x1a\n" +
	"\baccuracy\x18\x04 \x01(\tR\baccuracy\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\b \x01(\tR\x04city\x12\x1d\n" +
	"\n" +
	"ip_address\x18\t \x01(\tR\tipAddress\"}\n" +
	"\x12CheckUpdateRequest\x12!\n" +
	"\fposdevice_id\x18\x01 \x01(\tR\vposdeviceId\x12\x1f\n" +
	"\vapp_version\x18\x02 \x01(\tR\n" +
	"appVersion\x12#\n" +
	"\rbuild_version\x18\x03 \x01(\tR\fbuildVersion\"\xc3\x01\n" +
	"\x13CheckUpdateResponse\x12)\n" +
	"\x10update_available\x18\x01 \x01(\bR\x0fupdateAvailable\x12%\n" +
	"\x0elatest_version\x18\x02 \x01(\tR\rlatestVersion\x12!\n" +
	"\fdownload_url\x18\x03 \x01(\tR\vdownloadUrl\x12#\n" +
	"\rrelease_notes\x18\x04 \x01(\tR\freleaseNotes\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x05R\x04codeB\x1eZ\x1c/proto/posdevices;posdevicesb\x06proto3"

var (
	file_pos_devices_proto_rawDescOnce sync.Once
	file_pos_devices_proto_rawDescData []byte
)

func file_pos_devices_proto_rawDescGZIP() []byte {
	file_pos_devices_proto_rawDescOnce.Do(func() {
		file_pos_devices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pos_devices_proto_rawDesc), len(file_pos_devices_proto_rawDesc)))
	})
	return file_pos_devices_proto_rawDescData
}

var file_pos_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pos_devices_proto_goTypes = []any{
	(*RegisterPosDeviceRequest)(nil),       // 0: posdevices.RegisterPosDeviceRequest
	(*PosDevice)(nil),                      // 1: posdevices.PosDevice
	(*GetPosDevicesRequest)(nil),           // 2: posdevices.GetPosDevicesRequest
	(*GetPosDevicesResponse)(nil),          // 3: posdevices.GetPosDevicesResponse
	(*EditPosDeviceRequest)(nil),           // 4: posdevices.EditPosDeviceRequest
	(*RegisterLocationHistoryRequest)(nil), // 5: posdevices.RegisterLocationHistoryRequest
	(*LocationHistory)(nil),                // 6: posdevices.LocationHistory
	(*GetLocationHistorysRequest)(nil),     // 7: posdevices.GetLocationHistorysRequest
	(*GetLocationHistorysResponse)(nil),    // 8: posdevices.GetLocationHistorysResponse
	(*EditLocationHistoryRequest)(nil),     // 9: posdevices.EditLocationHistoryRequest
	(*CheckUpdateRequest)(nil),             // 10: posdevices.CheckUpdateRequest
	(*CheckUpdateResponse)(nil),            // 11: posdevices.CheckUpdateResponse
}
var file_pos_devices_proto_depIdxs = []int32{
	1, // 0: posdevices.GetPosDevicesResponse.posdevice:type_name -> posdevices.PosDevice
	6, // 1: posdevices.GetLocationHistorysResponse.location_history:type_name -> posdevices.LocationHistory
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pos_devices_proto_init() }
func file_pos_devices_proto_init() {
	if File_pos_devices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pos_devices_proto_rawDesc), len(file_pos_devices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pos_devices_proto_goTypes,
		DependencyIndexes: file_pos_devices_proto_depIdxs,
		MessageInfos:      file_pos_devices_proto_msgTypes,
	}.Build()
	File_pos_devices_proto = out.File
	file_pos_devices_proto_goTypes = nil
	file_pos_devices_proto_depIdxs = nil
}
