// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: terminal_type.proto

package terminaltype

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterTerminalTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TerminalModel string                 `protobuf:"bytes,2,opt,name=terminal_model,json=terminalModel,proto3" json:"terminal_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTerminalTypeRequest) Reset() {
	*x = RegisterTerminalTypeRequest{}
	mi := &file_terminal_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTerminalTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTerminalTypeRequest) ProtoMessage() {}

func (x *RegisterTerminalTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTerminalTypeRequest.ProtoReflect.Descriptor instead.
func (*RegisterTerminalTypeRequest) Descriptor() ([]byte, []int) {
	return file_terminal_type_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterTerminalTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterTerminalTypeRequest) GetTerminalModel() string {
	if x != nil {
		return x.TerminalModel
	}
	return ""
}

type TerminalType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TerminalModel string                 `protobuf:"bytes,2,opt,name=terminal_model,json=terminalModel,proto3" json:"terminal_model,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalType) Reset() {
	*x = TerminalType{}
	mi := &file_terminal_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalType) ProtoMessage() {}

func (x *TerminalType) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalType.ProtoReflect.Descriptor instead.
func (*TerminalType) Descriptor() ([]byte, []int) {
	return file_terminal_type_proto_rawDescGZIP(), []int{1}
}

func (x *TerminalType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TerminalType) GetTerminalModel() string {
	if x != nil {
		return x.TerminalModel
	}
	return ""
}

func (x *TerminalType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTerminalTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=searchQuery,proto3" json:"searchQuery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTerminalTypesRequest) Reset() {
	*x = GetTerminalTypesRequest{}
	mi := &file_terminal_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTerminalTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTerminalTypesRequest) ProtoMessage() {}

func (x *GetTerminalTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTerminalTypesRequest.ProtoReflect.Descriptor instead.
func (*GetTerminalTypesRequest) Descriptor() ([]byte, []int) {
	return file_terminal_type_proto_rawDescGZIP(), []int{2}
}

func (x *GetTerminalTypesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTerminalTypesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetTerminalTypesRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetTerminalTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalTypes []*TerminalType        `protobuf:"bytes,1,rep,name=terminal_types,json=terminalTypes,proto3" json:"terminal_types,omitempty"` // List of users
	TotalPages    int32                  `protobuf:"varint,2,opt,name=totalPages,proto3" json:"totalPages,omitempty"`                           // Total number of pages
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"`                         // Current page
	HasMore       bool                   `protobuf:"varint,4,opt,name=hasMore,proto3" json:"hasMore,omitempty"`                                 // Whether there are more pages
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTerminalTypesResponse) Reset() {
	*x = GetTerminalTypesResponse{}
	mi := &file_terminal_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTerminalTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTerminalTypesResponse) ProtoMessage() {}

func (x *GetTerminalTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTerminalTypesResponse.ProtoReflect.Descriptor instead.
func (*GetTerminalTypesResponse) Descriptor() ([]byte, []int) {
	return file_terminal_type_proto_rawDescGZIP(), []int{3}
}

func (x *GetTerminalTypesResponse) GetTerminalTypes() []*TerminalType {
	if x != nil {
		return x.TerminalTypes
	}
	return nil
}

func (x *GetTerminalTypesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetTerminalTypesResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetTerminalTypesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetTerminalTypesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type EditTerminalTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TerminalModel string                 `protobuf:"bytes,2,opt,name=terminal_model,json=terminalModel,proto3" json:"terminal_model,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditTerminalTypeRequest) Reset() {
	*x = EditTerminalTypeRequest{}
	mi := &file_terminal_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditTerminalTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditTerminalTypeRequest) ProtoMessage() {}

func (x *EditTerminalTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditTerminalTypeRequest.ProtoReflect.Descriptor instead.
func (*EditTerminalTypeRequest) Descriptor() ([]byte, []int) {
	return file_terminal_type_proto_rawDescGZIP(), []int{4}
}

func (x *EditTerminalTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditTerminalTypeRequest) GetTerminalModel() string {
	if x != nil {
		return x.TerminalModel
	}
	return ""
}

func (x *EditTerminalTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_terminal_type_proto protoreflect.FileDescriptor

const file_terminal_type_proto_rawDesc = "" +
	"\n" +
	"\x13terminal_type.proto\x12\fterminaltype\"X\n" +
	"\x1bRegisterTerminalTypeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eterminal_model\x18\x02 \x01(\tR\rterminalModel\"Y\n" +
	"\fTerminalType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eterminal_model\x18\x02 \x01(\tR\rterminalModel\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"k\n" +
	"\x17GetTerminalTypesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12 \n" +
	"\vsearchQuery\x18\x03 \x01(\tR\vsearchQuery\"\xcf\x01\n" +
	"\x18GetTerminalTypesResponse\x12A\n" +
	"\x0eterminal_types\x18\x01 \x03(\v2\x1a.terminaltype.TerminalTypeR\rterminalTypes\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12 \n" +
	"\vcurrentPage\x18\x03 \x01(\x05R\vcurrentPage\x12\x18\n" +
	"\ahasMore\x18\x04 \x01(\bR\ahasMore\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\"d\n" +
	"\x17EditTerminalTypeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eterminal_model\x18\x02 \x01(\tR\rterminalModel\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02idB\"Z /proto/terminaltype;terminaltypeb\x06proto3"

var (
	file_terminal_type_proto_rawDescOnce sync.Once
	file_terminal_type_proto_rawDescData []byte
)

func file_terminal_type_proto_rawDescGZIP() []byte {
	file_terminal_type_proto_rawDescOnce.Do(func() {
		file_terminal_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_terminal_type_proto_rawDesc), len(file_terminal_type_proto_rawDesc)))
	})
	return file_terminal_type_proto_rawDescData
}

var file_terminal_type_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_terminal_type_proto_goTypes = []any{
	(*RegisterTerminalTypeRequest)(nil), // 0: terminaltype.RegisterTerminalTypeRequest
	(*TerminalType)(nil),                // 1: terminaltype.TerminalType
	(*GetTerminalTypesRequest)(nil),     // 2: terminaltype.GetTerminalTypesRequest
	(*GetTerminalTypesResponse)(nil),    // 3: terminaltype.GetTerminalTypesResponse
	(*EditTerminalTypeRequest)(nil),     // 4: terminaltype.EditTerminalTypeRequest
}
var file_terminal_type_proto_depIdxs = []int32{
	1, // 0: terminaltype.GetTerminalTypesResponse.terminal_types:type_name -> terminaltype.TerminalType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_terminal_type_proto_init() }
func file_terminal_type_proto_init() {
	if File_terminal_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_terminal_type_proto_rawDesc), len(file_terminal_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_terminal_type_proto_goTypes,
		DependencyIndexes: file_terminal_type_proto_depIdxs,
		MessageInfos:      file_terminal_type_proto_msgTypes,
	}.Build()
	File_terminal_type_proto = out.File
	file_terminal_type_proto_goTypes = nil
	file_terminal_type_proto_depIdxs = nil
}
