// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: app.proto

package app

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAppRequest) Reset() {
	*x = RegisterAppRequest{}
	mi := &file_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAppRequest) ProtoMessage() {}

func (x *RegisterAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAppRequest.ProtoReflect.Descriptor instead.
func (*RegisterAppRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAppRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{1}
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *App) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=searchQuery,proto3" json:"searchQuery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppsRequest) Reset() {
	*x = GetAppsRequest{}
	mi := &file_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppsRequest) ProtoMessage() {}

func (x *GetAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppsRequest.ProtoReflect.Descriptor instead.
func (*GetAppsRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{2}
}

func (x *GetAppsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAppsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetAppsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           []*App                 `protobuf:"bytes,1,rep,name=app,proto3" json:"app,omitempty"`                  // List of users
	TotalPages    int32                  `protobuf:"varint,2,opt,name=totalPages,proto3" json:"totalPages,omitempty"`   // Total number of pages
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"` // Current page
	HasMore       bool                   `protobuf:"varint,4,opt,name=hasMore,proto3" json:"hasMore,omitempty"`         // Whether there are more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppsResponse) Reset() {
	*x = GetAppsResponse{}
	mi := &file_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppsResponse) ProtoMessage() {}

func (x *GetAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppsResponse.ProtoReflect.Descriptor instead.
func (*GetAppsResponse) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{3}
}

func (x *GetAppsResponse) GetApp() []*App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *GetAppsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetAppsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetAppsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditAppRequest) Reset() {
	*x = EditAppRequest{}
	mi := &file_app_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAppRequest) ProtoMessage() {}

func (x *EditAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAppRequest.ProtoReflect.Descriptor instead.
func (*EditAppRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{4}
}

func (x *EditAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditAppRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EditAppRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RegisterAppVersionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	VersionNumber  string                 `protobuf:"bytes,2,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	BuildNumber    string                 `protobuf:"bytes,3,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	ReleaseNotes   string                 `protobuf:"bytes,4,opt,name=release_notes,json=releaseNotes,proto3" json:"release_notes,omitempty"`
	Apk            []byte                 `protobuf:"bytes,5,opt,name=apk,proto3" json:"apk,omitempty"`
	FileSizeBytes  string                 `protobuf:"bytes,6,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	IsLatestStable bool                   `protobuf:"varint,7,opt,name=is_latest_stable,json=isLatestStable,proto3" json:"is_latest_stable,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterAppVersionRequest) Reset() {
	*x = RegisterAppVersionRequest{}
	mi := &file_app_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAppVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAppVersionRequest) ProtoMessage() {}

func (x *RegisterAppVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAppVersionRequest.ProtoReflect.Descriptor instead.
func (*RegisterAppVersionRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterAppVersionRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RegisterAppVersionRequest) GetVersionNumber() string {
	if x != nil {
		return x.VersionNumber
	}
	return ""
}

func (x *RegisterAppVersionRequest) GetBuildNumber() string {
	if x != nil {
		return x.BuildNumber
	}
	return ""
}

func (x *RegisterAppVersionRequest) GetReleaseNotes() string {
	if x != nil {
		return x.ReleaseNotes
	}
	return ""
}

func (x *RegisterAppVersionRequest) GetApk() []byte {
	if x != nil {
		return x.Apk
	}
	return nil
}

func (x *RegisterAppVersionRequest) GetFileSizeBytes() string {
	if x != nil {
		return x.FileSizeBytes
	}
	return ""
}

func (x *RegisterAppVersionRequest) GetIsLatestStable() bool {
	if x != nil {
		return x.IsLatestStable
	}
	return false
}

type AppVersion struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	VersionNumber  string                 `protobuf:"bytes,2,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	BuildNumber    string                 `protobuf:"bytes,3,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	ReleaseNotes   string                 `protobuf:"bytes,4,opt,name=release_notes,json=releaseNotes,proto3" json:"release_notes,omitempty"`
	FilePath       string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileSizeBytes  string                 `protobuf:"bytes,6,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	Checksum       string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	IsActive       bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsLatestStable bool                   `protobuf:"varint,9,opt,name=is_latest_stable,json=isLatestStable,proto3" json:"is_latest_stable,omitempty"`
	ReleasedAt     string                 `protobuf:"bytes,10,opt,name=released_at,json=releasedAt,proto3" json:"released_at,omitempty"`
	VersionId      string                 `protobuf:"bytes,11,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppVersion) Reset() {
	*x = AppVersion{}
	mi := &file_app_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppVersion) ProtoMessage() {}

func (x *AppVersion) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppVersion.ProtoReflect.Descriptor instead.
func (*AppVersion) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{6}
}

func (x *AppVersion) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppVersion) GetVersionNumber() string {
	if x != nil {
		return x.VersionNumber
	}
	return ""
}

func (x *AppVersion) GetBuildNumber() string {
	if x != nil {
		return x.BuildNumber
	}
	return ""
}

func (x *AppVersion) GetReleaseNotes() string {
	if x != nil {
		return x.ReleaseNotes
	}
	return ""
}

func (x *AppVersion) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *AppVersion) GetFileSizeBytes() string {
	if x != nil {
		return x.FileSizeBytes
	}
	return ""
}

func (x *AppVersion) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *AppVersion) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *AppVersion) GetIsLatestStable() bool {
	if x != nil {
		return x.IsLatestStable
	}
	return false
}

func (x *AppVersion) GetReleasedAt() string {
	if x != nil {
		return x.ReleasedAt
	}
	return ""
}

func (x *AppVersion) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type GetAppVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=searchQuery,proto3" json:"searchQuery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppVersionsRequest) Reset() {
	*x = GetAppVersionsRequest{}
	mi := &file_app_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppVersionsRequest) ProtoMessage() {}

func (x *GetAppVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppVersionsRequest.ProtoReflect.Descriptor instead.
func (*GetAppVersionsRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{7}
}

func (x *GetAppVersionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAppVersionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetAppVersionsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetAppVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppVersion    []*AppVersion          `protobuf:"bytes,1,rep,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"` // List of users
	TotalPages    int32                  `protobuf:"varint,2,opt,name=totalPages,proto3" json:"totalPages,omitempty"`                  // Total number of pages
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"`                // Current page
	HasMore       bool                   `protobuf:"varint,4,opt,name=hasMore,proto3" json:"hasMore,omitempty"`                        // Whether there are more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppVersionsResponse) Reset() {
	*x = GetAppVersionsResponse{}
	mi := &file_app_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppVersionsResponse) ProtoMessage() {}

func (x *GetAppVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppVersionsResponse.ProtoReflect.Descriptor instead.
func (*GetAppVersionsResponse) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{8}
}

func (x *GetAppVersionsResponse) GetAppVersion() []*AppVersion {
	if x != nil {
		return x.AppVersion
	}
	return nil
}

func (x *GetAppVersionsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetAppVersionsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetAppVersionsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditAppVersionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	VersionNumber  string                 `protobuf:"bytes,2,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	BuildNumber    string                 `protobuf:"bytes,3,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	ReleaseNotes   string                 `protobuf:"bytes,4,opt,name=release_notes,json=releaseNotes,proto3" json:"release_notes,omitempty"`
	Apk            []byte                 `protobuf:"bytes,5,opt,name=apk,proto3" json:"apk,omitempty"`
	IsActive       bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsLatestStable string                 `protobuf:"bytes,9,opt,name=is_latest_stable,json=isLatestStable,proto3" json:"is_latest_stable,omitempty"`
	VersionId      string                 `protobuf:"bytes,10,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EditAppVersionRequest) Reset() {
	*x = EditAppVersionRequest{}
	mi := &file_app_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditAppVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAppVersionRequest) ProtoMessage() {}

func (x *EditAppVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAppVersionRequest.ProtoReflect.Descriptor instead.
func (*EditAppVersionRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{9}
}

func (x *EditAppVersionRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *EditAppVersionRequest) GetVersionNumber() string {
	if x != nil {
		return x.VersionNumber
	}
	return ""
}

func (x *EditAppVersionRequest) GetBuildNumber() string {
	if x != nil {
		return x.BuildNumber
	}
	return ""
}

func (x *EditAppVersionRequest) GetReleaseNotes() string {
	if x != nil {
		return x.ReleaseNotes
	}
	return ""
}

func (x *EditAppVersionRequest) GetApk() []byte {
	if x != nil {
		return x.Apk
	}
	return nil
}

func (x *EditAppVersionRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *EditAppVersionRequest) GetIsLatestStable() string {
	if x != nil {
		return x.IsLatestStable
	}
	return ""
}

func (x *EditAppVersionRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

var File_app_proto protoreflect.FileDescriptor

const file_app_proto_rawDesc = "" +
	"\n" +
	"\tapp.proto\x12\x03app\"J\n" +
	"\x12RegisterAppRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"K\n" +
	"\x03App\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\"b\n" +
	"\x0eGetAppsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12 \n" +
	"\vsearchQuery\x18\x03 \x01(\tR\vsearchQuery\"\x89\x01\n" +
	"\x0fGetAppsResponse\x12\x1a\n" +
	"\x03app\x18\x01 \x03(\v2\b.app.AppR\x03app\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12 \n" +
	"\vcurrentPage\x18\x03 \x01(\x05R\vcurrentPage\x12\x18\n" +
	"\ahasMore\x18\x04 \x01(\bR\ahasMore\"V\n" +
	"\x0eEditAppRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\"\x85\x02\n" +
	"\x19RegisterAppVersionRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12%\n" +
	"\x0eversion_number\x18\x02 \x01(\tR\rversionNumber\x12!\n" +
	"\fbuild_number\x18\x03 \x01(\tR\vbuildNumber\x12#\n" +
	"\rrelease_notes\x18\x04 \x01(\tR\freleaseNotes\x12\x10\n" +
	"\x03apk\x18\x05 \x01(\fR\x03apk\x12&\n" +
	"\x0ffile_size_bytes\x18\x06 \x01(\tR\rfileSizeBytes\x12(\n" +
	"\x10is_latest_stable\x18\a \x01(\bR\x0eisLatestStable\"\xfa\x02\n" +
	"\n" +
	"AppVersion\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12%\n" +
	"\x0eversion_number\x18\x02 \x01(\tR\rversionNumber\x12!\n" +
	"\fbuild_number\x18\x03 \x01(\tR\vbuildNumber\x12#\n" +
	"\rrelease_notes\x18\x04 \x01(\tR\freleaseNotes\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\x12&\n" +
	"\x0ffile_size_bytes\x18\x06 \x01(\tR\rfileSizeBytes\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12(\n" +
	"\x10is_latest_stable\x18\t \x01(\bR\x0eisLatestStable\x12\x1f\n" +
	"\vreleased_at\x18\n" +
	" \x01(\tR\n" +
	"releasedAt\x12\x1d\n" +
	"\n" +
	"version_id\x18\v \x01(\tR\tversionId\"i\n" +
	"\x15GetAppVersionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12 \n" +
	"\vsearchQuery\x18\x03 \x01(\tR\vsearchQuery\"\xa6\x01\n" +
	"\x16GetAppVersionsResponse\x120\n" +
	"\vapp_version\x18\x01 \x03(\v2\x0f.app.AppVersionR\n" +
	"appVersion\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12 \n" +
	"\vcurrentPage\x18\x03 \x01(\x05R\vcurrentPage\x12\x18\n" +
	"\ahasMore\x18\x04 \x01(\bR\ahasMore\"\x95\x02\n" +
	"\x15EditAppVersionRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12%\n" +
	"\x0eversion_number\x18\x02 \x01(\tR\rversionNumber\x12!\n" +
	"\fbuild_number\x18\x03 \x01(\tR\vbuildNumber\x12#\n" +
	"\rrelease_notes\x18\x04 \x01(\tR\freleaseNotes\x12\x10\n" +
	"\x03apk\x18\x05 \x01(\fR\x03apk\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12(\n" +
	"\x10is_latest_stable\x18\t \x01(\tR\x0eisLatestStable\x12\x1d\n" +
	"\n" +
	"version_id\x18\n" +
	" \x01(\tR\tversionIdB\x10Z\x0e/proto/app;appb\x06proto3"

var (
	file_app_proto_rawDescOnce sync.Once
	file_app_proto_rawDescData []byte
)

func file_app_proto_rawDescGZIP() []byte {
	file_app_proto_rawDescOnce.Do(func() {
		file_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_proto_rawDesc), len(file_app_proto_rawDesc)))
	})
	return file_app_proto_rawDescData
}

var file_app_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_app_proto_goTypes = []any{
	(*RegisterAppRequest)(nil),        // 0: app.RegisterAppRequest
	(*App)(nil),                       // 1: app.App
	(*GetAppsRequest)(nil),            // 2: app.GetAppsRequest
	(*GetAppsResponse)(nil),           // 3: app.GetAppsResponse
	(*EditAppRequest)(nil),            // 4: app.EditAppRequest
	(*RegisterAppVersionRequest)(nil), // 5: app.RegisterAppVersionRequest
	(*AppVersion)(nil),                // 6: app.AppVersion
	(*GetAppVersionsRequest)(nil),     // 7: app.GetAppVersionsRequest
	(*GetAppVersionsResponse)(nil),    // 8: app.GetAppVersionsResponse
	(*EditAppVersionRequest)(nil),     // 9: app.EditAppVersionRequest
}
var file_app_proto_depIdxs = []int32{
	1, // 0: app.GetAppsResponse.app:type_name -> app.App
	6, // 1: app.GetAppVersionsResponse.app_version:type_name -> app.AppVersion
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_proto_init() }
func file_app_proto_init() {
	if File_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_proto_rawDesc), len(file_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_proto_goTypes,
		DependencyIndexes: file_app_proto_depIdxs,
		MessageInfos:      file_app_proto_msgTypes,
	}.Build()
	File_app_proto = out.File
	file_app_proto_goTypes = nil
	file_app_proto_depIdxs = nil
}
